export default [
    {
        'id': 1,
        'title': 'Tinsels',
        'description': '',
        'schedule_duration': 50,
        'schedule_daytime': JSON.stringify([]),
        'start_time': '00:00',
        'timezone': null,
        'logo_enable': 0,
        'logo': null,
        'logo_link': 'http://localhost:8000/channel_logos/imd3MO0cuJ7Teh99.jpeg',
        'logo_position': 'right',
        'color': '#000000',
        'twitter': null,
        'privacy': 'anywhere',
        'privacy_domain': null,
        'ad_tag_url': null,
        'channel_type': 'Playlist (On demand)',
        'channel_hash': 'xvatdqcxscc6na4pmvajia8oms6wsasd',
        'stream_name': '0vlajo7xodfhxxjf35u12fb8icxktu3a',
        'roku_link': 'http://localhost:8000/channel/w/xvatdqcxscc6na4pmvajia8oms6wsasd?format=roku_json',
        'total_vidoes': 10,
        'total_views': 4580,
        'thumbnail': null
    },
    {
        'id': 2,
        'title': 'Zion Tv',
        'description': '',
        'schedule_duration': 50,
        'schedule_daytime': JSON.stringify([]),
        'start_time': '00:00',
        'timezone': null,
        'logo_enable': 0,
        'logo': null,
        'logo_link': 'http://localhost:8000/channel_logos/imd3MO0cuJ7Teh99.jpeg',
        'logo_position': 'right',
        'color': '#000000',
        'twitter': null,
        'privacy': 'anywhere',
        'privacy_domain': null,
        'ad_tag_url': null,
        'channel_type': 'Scheduled (Linear)',
        'channel_hash': 'xvatdqcxscc6na4pmvajia8oms6wsasd',
        'stream_name': '0vlajo7xodfhxxjf35u12fb8icxktu3a',
        'roku_link': 'http://localhost:8000/channel/w/xvatdqcxscc6na4pmvajia8oms6wsasd?format=roku_json',
        'total_vidoes': 25,
        'total_views': 3428,
        'thumbnail': null
    },
    {
        'id': 3,
        'title': 'Sporty Tv',
        'description': '',
        'schedule_duration': 50,
        'schedule_daytime': JSON.stringify([]),
        'start_time': '00:00',
        'timezone': null,
        'logo_enable': 0,
        'logo': null,
        'logo_link': 'http://localhost:8000/channel_logos/imd3MO0cuJ7Teh99.jpeg',
        'logo_position': 'right',
        'color': '#000000',
        'twitter': null,
        'privacy': 'anywhere',
        'privacy_domain': null,
        'ad_tag_url': null,
        'channel_type': 'Scheduled (Linear)',
        'channel_hash': 'xvatdqcxscc6na4pmvajia8oms6wsasd',
        'stream_name': '0vlajo7xodfhxxjf35u12fb8icxktu3a',
        'roku_link': 'http://localhost:8000/channel/w/xvatdqcxscc6na4pmvajia8oms6wsasd?format=roku_json',
        'total_vidoes': 18,
        'total_views': 5446,
        'thumbnail': null
    },
    {
        'id': 4,
        'title': 'Food Tricks',
        'description': '',
        'schedule_duration': 50,
        'schedule_daytime': JSON.stringify([]),
        'start_time': '00:00',
        'timezone': null,
        'logo_enable': 0,
        'logo': null,
        'logo_link': 'http://localhost:8000/channel_logos/imd3MO0cuJ7Teh99.jpeg',
        'logo_position': 'right',
        'color': '#000000',
        'twitter': null,
        'privacy': 'anywhere',
        'privacy_domain': null,
        'ad_tag_url': null,
        'channel_type': 'Scheduled (Linear)',
        'channel_hash': 'xvatdqcxscc6na4pmvajia8oms6wsasd',
        'stream_name': '0vlajo7xodfhxxjf35u12fb8icxktu3a',
        'roku_link': 'http://localhost:8000/channel/w/xvatdqcxscc6na4pmvajia8oms6wsasd?format=roku_json',
        'total_vidoes': 32,
        'total_views': 10250,
        'thumbnail': null
    },
    {
        'id': 5,
        'title': 'Animal Farm',
        'description': '',
        'schedule_duration': 50,
        'schedule_daytime': JSON.stringify([]),
        'start_time': '00:00',
        'timezone': null,
        'logo_enable': 0,
        'logo': null,
        'logo_link': 'http://localhost:8000/channel_logos/imd3MO0cuJ7Teh99.jpeg',
        'logo_position': 'right',
        'color': '#000000',
        'twitter': null,
        'privacy': 'anywhere',
        'privacy_domain': null,
        'ad_tag_url': null,
        'channel_type': 'Playlist (On demand)',
        'channel_hash': 'xvatdqcxscc6na4pmvajia8oms6wsasd',
        'stream_name': '0vlajo7xodfhxxjf35u12fb8icxktu3a',
        'roku_link': 'http://localhost:8000/channel/w/xvatdqcxscc6na4pmvajia8oms6wsasd?format=roku_json',
        'total_vidoes': 16,
        'total_views': 2473,
        'thumbnail': null
    },
    {
        'id': 6,
        'title': 'Animation Arena',
        'description': '',
        'schedule_duration': 50,
        'schedule_daytime': JSON.stringify([]),
        'start_time': '00:00',
        'timezone': null,
        'logo_enable': 0,
        'logo': null,
        'logo_link': 'http://localhost:8000/channel_logos/imd3MO0cuJ7Teh99.jpeg',
        'logo_position': 'right',
        'color': '#000000',
        'twitter': null,
        'privacy': 'anywhere',
        'privacy_domain': null,
        'ad_tag_url': null,
        'channel_type': 'Playlist (On demand)',
        'channel_hash': 'xvatdqcxscc6na4pmvajia8oms6wsasd',
        'stream_name': '0vlajo7xodfhxxjf35u12fb8icxktu3a',
        'roku_link': 'http://localhost:8000/channel/w/xvatdqcxscc6na4pmvajia8oms6wsasd?format=roku_json',
        'total_vidoes': 20,
        'total_views': 8626,
        'thumbnail': null
    },
    {
        'id': 7,
        'title': 'Tech Century',
        'description': '',
        'schedule_duration': 50,
        'schedule_daytime': JSON.stringify([]),
        'start_time': '00:00',
        'timezone': null,
        'logo_enable': 0,
        'logo': null,
        'logo_link': 'http://localhost:8000/channel_logos/imd3MO0cuJ7Teh99.jpeg',
        'logo_position': 'right',
        'color': '#000000',
        'twitter': null,
        'privacy': 'anywhere',
        'privacy_domain': null,
        'ad_tag_url': null,
        'channel_type': 'Scheduled (Linear)',
        'channel_hash': 'xvatdqcxscc6na4pmvajia8oms6wsasd',
        'stream_name': '0vlajo7xodfhxxjf35u12fb8icxktu3a',
        'roku_link': 'http://localhost:8000/channel/w/xvatdqcxscc6na4pmvajia8oms6wsasd?format=roku_json',
        'total_vidoes': 7,
        'total_views': 14934,
        'thumbnail': null
    },
]